server:
  port: 0   # Random port géré par Eureka

spring:
  application:
    name: fleet-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    prefer-ip-address: true
